import os
from PIL import ImageFont

def ttf_to_gfx(font_path, font_size, font_name):
    font = ImageFont.truetype(font_path, font_size)
    ascent, descent = font.getmetrics()
    
    first = 32
    last = 126
    
    bitmaps = []
    glyphs = []
    
    current_offset = 0
    
    for code in range(first, last + 1):
        char = chr(code)
        bbox = font.getbbox(char)
        length = font.getlength(char)
        x_advance = int(round(length))
        
        # If character has no size (like space)
        if bbox is None or bbox[2] <= bbox[0] or bbox[3] <= bbox[1]:
            glyphs.append({
                'offset': current_offset,
                'width': 0,
                'height': 0,
                'xAdvance': x_advance,
                'xOffset': 0,
                'yOffset': 0
            })
            continue
            
        left, top, right, bottom = bbox
        width = right - left
        height = bottom - top
        x_offset = left
        y_offset = top - ascent
        
        mask = font.getmask(char, mode='L')
        
        # Extract pixels
        pixels = []
        for y in range(height):
            for x in range(width):
                val = mask.getpixel((x, y))
                pixels.append(1 if val > 127 else 0)
                
        # Pack pixels into bytes
        glyph_bytes = []
        current_byte = 0
        bits_written = 0
        for p in pixels:
            current_byte = (current_byte << 1) | p
            bits_written += 1
            if bits_written == 8:
                glyph_bytes.append(current_byte)
                current_byte = 0
                bits_written = 0
        if bits_written > 0:
            current_byte = current_byte << (8 - bits_written)
            glyph_bytes.append(current_byte)
            
        glyphs.append({
            'offset': current_offset,
            'width': width,
            'height': height,
            'xAdvance': x_advance,
            'xOffset': x_offset,
            'yOffset': y_offset
        })
        
        bitmaps.extend(glyph_bytes)
        current_offset += len(glyph_bytes)
        
    struct_name = f"{font_name}{font_size}pt7b"
    
    out = []
    out.append(f"// Font generated by Python script from {os.path.basename(font_path)}")
    out.append(f"// Size: {font_size}pt")
    out.append("")
    out.append("#pragma once")
    out.append("#include <stdint.h>")
    out.append("#ifdef ESP32")
    out.append("#include <pgmspace.h>")
    out.append("#else")
    out.append("#define PROGMEM")
    out.append("#endif")
    out.append("#include <Fonts/GFXFF/gfxfont.h>")
    out.append("")
    
    # Bitmap array
    out.append(f"const uint8_t {struct_name}Bitmaps[] PROGMEM = {{")
    for i in range(0, len(bitmaps), 12):
        chunk = bitmaps[i:i+12]
        hex_str = ", ".join(f"0x{b:02X}" for b in chunk)
        comma = "," if i + 12 < len(bitmaps) else ""
        out.append(f"    {hex_str}{comma}")
    out.append("};")
    out.append("")
    
    # Glyphs array
    out.append(f"const GFXglyph {struct_name}Glyphs[] PROGMEM = {{")
    for idx, g in enumerate(glyphs):
        comma = "," if idx + 1 < len(glyphs) else ""
        char_comment = f" // '{chr(first + idx)}'" if first + idx >= 32 and first + idx <= 126 else ""
        out.append(f"    {{ {g['offset']:5}, {g['width']:3}, {g['height']:3}, {g['xAdvance']:3}, {g['xOffset']:4}, {g['yOffset']:4} }}{comma}{char_comment}")
    out.append("};")
    out.append("")
    
    # Font structure
    y_advance = ascent + descent
    out.append(f"const GFXfont {struct_name} PROGMEM = {{")
    out.append(f"    (uint8_t *){struct_name}Bitmaps,")
    out.append(f"    (GFXglyph *){struct_name}Glyphs,")
    out.append(f"    {first}, {last}, {y_advance}")
    out.append("};")
    out.append("")
    
    return "\n".join(out)

def main():
    font_path = "E:\\AI\\Longboard-Display\\BebasNeue.ttf"
    sizes = [18, 24, 40, 80]
    output_dir = "E:\\AI\\Longboard-Display\\src"
    
    if not os.path.exists(output_dir):
        os.makedirs(output_dir)
        
    for size in sizes:
        print(f"Generating {size}pt font...")
        header_content = ttf_to_gfx(font_path, size, "BebasNeue")
        output_file = os.path.join(output_dir, f"BebasNeue{size}.h")
        with open(output_file, 'w', encoding='utf-8') as f:
            f.write(header_content)
        print(f"Saved: {output_file}")
    
    print("All fonts generated successfully!")

if __name__ == '__main__':
    main()
