#!/usr/bin/env python3
"""
PlatformIO pre-build hook: generate src/version.h from version.txt + git state.

The single source of truth for the human-facing version is version.txt
(semantic MAJOR.MINOR.PATCH). Bump it as part of each meaningful change/fix.
This script stamps that semver together with the current git short hash, a
"-dirty" marker when there are uncommitted changes, and the build date, so every
flashed build is uniquely identifiable on the System page.

src/version.h is generated (gitignored) and rewritten only when its contents
actually change, so it does not force needless recompiles.
"""
import os
import subprocess
import datetime

Import("env")  # noqa: F821  (provided by PlatformIO/SCons)


def _git(args, default=""):
    try:
        return subprocess.check_output(
            ["git"] + args, stderr=subprocess.DEVNULL
        ).decode().strip()
    except Exception:
        return default


proj = env["PROJECT_DIR"]  # noqa: F821

semver = "0.0.0"
vpath = os.path.join(proj, "version.txt")
if os.path.exists(vpath):
    with open(vpath) as f:
        semver = (f.read().strip() or semver)

short = _git(["rev-parse", "--short", "HEAD"], "nogit")
dirty = 1 if _git(["status", "--porcelain"]) else 0
date = datetime.date.today().isoformat()

version = "v" + semver
full = "v%s %s%s" % (semver, short, "-dirty" if dirty else "")

content = "\n".join([
    "#pragma once",
    "// AUTO-GENERATED by scripts/gen_version.py on each build. Do not edit by hand.",
    "// Source of truth for the semver is version.txt at the repo root.",
    '#define FW_VERSION_SEMVER "%s"' % semver,
    '#define FW_VERSION_HASH   "%s"' % short,
    "#define FW_VERSION_DIRTY  %d" % dirty,
    '#define FW_VERSION_DATE   "%s"' % date,
    '#define FW_VERSION        "%s"' % version,
    '#define FW_VERSION_FULL   "%s"' % full,
    "",
])

out = os.path.join(proj, "src", "version.h")
old = ""
if os.path.exists(out):
    with open(out) as f:
        old = f.read()
if old != content:
    with open(out, "w") as f:
        f.write(content)

print("gen_version: %s" % full)
